In [1]:
import numpy as np
import pandas as pd

In [2]:
dt=pd.read_csv("D:\MLlab\ML\diets.csv")
dt

Calories  CaloriesfromFat  TotalFat  TotalFat.1  Sodium  Sodium.1  \
0         20                0       0.0           0       0         0   
1         25                0       0.0           0      40         2   
2         45                0       0.5           1      80         3   
3         30                0       0.0           0      60         3   
4         25                0       0.0           0      30         1   
..       ...              ...       ...         ...     ...       ...   
56       140               10       1.0           2     310        13   
57       100               10       1.5           2     240        10   
58       120               50       6.0           9     100         4   
59       110               20       2.5           4      30         1   
60       130               15       1.5           2      40         2   

    Potassium  Potassium.1  TotalCarbohydrate  TotalCarbohydrate.1  ...  \
0         230            7                  4                    1  ...   
1         220            6                  6                    2  ...   
2         460           13                  8                    3  ...   
3         250            7                  7                    2  ...   
4         270            8                  5                    2  ...   
..        ...          ...                ...                  ...  ...   
56        430           12                  5                    2  ...   
57        220            6                  0                    0  ...   
58        310            9                  0                    0  ...   
59        360           10                  0                    0  ...   
60        480           14                  0                    0  ...   

    Protein  VitaminA  VitaminC  Calcium  Iron  SaturatedFat  SaturatedFat.1  \
0         2        10        15        2     2           0.0               0   
1         1         4       190        2     4           0.0               0   
2         4         6       220        6     6           0.0               0   
3         1       110        10        2     2           0.0               0   
4         2         0       100        2     2           0.0               0   
..      ...       ...       ...      ...   ...           ...             ...   
56       27         2         0        4    14           0.0               0   
57       21         4         4        6    10           0.0               0   
58       16         2         2        0     6           1.5               8   
59       22         0         2        0     2           1.0               5   
60       26         2         2        2     4           0.0               0   

    Cholesterol  Cholesterol.1     FoodType  
0             0              0  Vegetables   
1             0              0  Vegetables   
2             0              0  Vegetables   
3             0              0  Vegetables   
4             0              0  Vegetables   
..          ...            ...          ...  
56           65             22     Seafood   
57          170             57     Seafood   
58           40             13     Seafood   
59           75             25     Seafood   
60           50             17     Seafood   

[61 rows x 23 columns]

In [3]:
dt["FoodType"]=dt["FoodType"].astype("category")
dt["FoodType"]=dt["FoodType"].cat.codes

In [4]:
x=dt.iloc[:,0:-1].values
x

array([[ 20. ,   0. ,   0. , ...,   0. ,   0. ,   0. ],
       [ 25. ,   0. ,   0. , ...,   0. ,   0. ,   0. ],
       [ 45. ,   0. ,   0.5, ...,   0. ,   0. ,   0. ],
       ...,
       [120. ,  50. ,   6. , ...,   8. ,  40. ,  13. ],
       [110. ,  20. ,   2.5, ...,   5. ,  75. ,  25. ],
       [130. ,  15. ,   1.5, ...,   0. ,  50. ,  17. ]])

In [5]:
y=dt.iloc[:,-1].values
y

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.15,random_state=0)

In [7]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=7)

In [8]:
classifier

KNeighborsClassifier(n_neighbors=7)

In [9]:
classifier.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=7)

In [10]:
y_predict=classifier.predict(x_test)
y_predict

array([2, 0, 1, 0, 2, 1, 0, 1, 1, 1], dtype=int8)

In [11]:
from sklearn.metrics import classification_report,confusion_matrix
cnf_matrix=confusion_matrix(y_test,y_predict)

In [12]:
cnf_matrix

array([[3, 1, 1],
       [0, 3, 0],
       [0, 1, 1]], dtype=int64)

In [13]:
((cnf_matrix[0,0]+cnf_matrix[1,1])/np.sum(cnf_matrix))*100

60.0

In [16]:
new_observation=[20,0,0.0,0,15,0,300,9,3,1,3,0,2,0,2,0.0,0,0,0,0,0,0]


In [17]:
y_predict=classifier.predict([new_observation])
y_predict

array([2], dtype=int8)