In [1]:
import numpy as np
import pandas as pd

In [2]:
house=pd.read_csv("D:\lab\ML\housepred1.csv")

In [3]:
house

Id Street  YearBuilt  BedroomAbvGr  KitchenAbvGr KitchenQual  \
0        1   Pave       2003             3             1          Gd   
1        2   Pave       1976             3             1          TA   
2        3   Pave       2001             3             1          Gd   
3        4   Pave       1915             3             1          Gd   
4        5   Pave       2000             4             1          Gd   
...    ...    ...        ...           ...           ...         ...   
1455  1456   Pave       1999             3             1          TA   
1456  1457   Pave       1978             3             1          TA   
1457  1458   Pave       1941             4             1          Gd   
1458  1459   Pave       1950             2             1          Gd   
1459  1460   Pave       1965             3             1          TA   

      TotRmsAbvGrd Functional  Fireplaces GarageType  GarageCars  GarageArea  \
0                8        Typ           0     Attchd           2         548   
1                6        Typ           1     Attchd           2         460   
2                6        Typ           1     Attchd           2         608   
3                7        Typ           1     Detchd           3         642   
4                9        Typ           1     Attchd           3         836   
...            ...        ...         ...        ...         ...         ...   
1455             7        Typ           1     Attchd           2         460   
1456             7       Min1           2     Attchd           2         500   
1457             9        Typ           2     Attchd           1         252   
1458             5        Typ           0     Attchd           1         240   
1459             6        Typ           0     Attchd           1         276   

     PavedDrive  WoodDeckSF  OpenPorchSF  EnclosedPorch  YrSold SaleType  \
0             Y           0           61              0    2008       WD   
1             Y         298            0              0    2007       WD   
2             Y           0           42              0    2008       WD   
3             Y           0           35            272    2006       WD   
4             Y         192           84              0    2008       WD   
...         ...         ...          ...            ...     ...      ...   
1455          Y           0           40              0    2007       WD   
1456          Y         349            0              0    2010       WD   
1457          Y           0           60              0    2010       WD   
1458          Y         366            0            112    2010       WD   
1459          Y         736           68              0    2008       WD   

     SaleCondition  SalePrice  
0           Normal     208500  
1           Normal     181500  
2           Normal     223500  
3          Abnorml     140000  
4           Normal     250000  
...            ...        ...  
1455        Normal     175000  
1456        Normal     210000  
1457        Normal     266500  
1458        Normal     142125  
1459        Normal     147500  

[1460 rows x 20 columns]

In [4]:
from sklearn.preprocessing import LabelEncoder
lr=LabelEncoder()

In [5]:
house["Street"]=lr.fit_transform(house["Street"])
house["KitchenQual"]=lr.fit_transform(house["KitchenQual"])
house["Functional"]=lr.fit_transform(house["Functional"])
house["SaleCondition"]=lr.fit_transform(house["SaleCondition"])
house["PavedDrive"]=lr.fit_transform(house["PavedDrive"])
house["SaleType"]=lr.fit_transform(house["SaleType"])
house.head()

Id  Street  YearBuilt  BedroomAbvGr  KitchenAbvGr  KitchenQual  \
0   1       1       2003             3             1            2   
1   2       1       1976             3             1            3   
2   3       1       2001             3             1            2   
3   4       1       1915             3             1            2   
4   5       1       2000             4             1            2   

   TotRmsAbvGrd  Functional  Fireplaces GarageType  GarageCars  GarageArea  \
0             8           6           0     Attchd           2         548   
1             6           6           1     Attchd           2         460   
2             6           6           1     Attchd           2         608   
3             7           6           1     Detchd           3         642   
4             9           6           1     Attchd           3         836   

   PavedDrive  WoodDeckSF  OpenPorchSF  EnclosedPorch  YrSold  SaleType  \
0           2           0           61              0    2008         8   
1           2         298            0              0    2007         8   
2           2           0           42              0    2008         8   
3           2           0           35            272    2006         8   
4           2         192           84              0    2008         8   

   SaleCondition  SalePrice  
0              4     208500  
1              4     181500  
2              4     223500  
3              0     140000  
4              4     250000

In [6]:
x=house.drop('GarageType',axis=1,inplace=True)

In [7]:
x=house.iloc[:,0:-1].values
x

array([[   1,    1, 2003, ..., 2008,    8,    4],
       [   2,    1, 1976, ..., 2007,    8,    4],
       [   3,    1, 2001, ..., 2008,    8,    4],
       ...,
       [1458,    1, 1941, ..., 2010,    8,    4],
       [1459,    1, 1950, ..., 2010,    8,    4],
       [1460,    1, 1965, ..., 2008,    8,    4]], dtype=int64)

In [8]:
y=house.iloc[:,-1].values
y

array([208500, 181500, 223500, ..., 266500, 142125, 147500], dtype=int64)

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [10]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [11]:
y_predict=lr.predict(x_test)
y_predict

array([152018.78832121, 170999.07977351, 148897.71468587, 217766.57487945,
       115754.59184851,  42495.27762826, 222640.7987493 , 173145.92966466,
       354775.7694951 , 153166.5729658 , 205823.3421545 , 137114.05088468,
       252271.77715408, 156123.93884377, 123565.98663602, 109224.17591066,
       249821.04164365,  88134.51561287, 143945.63419375, 163731.66634582,
       142901.99594672, 182376.11561638,  94844.36278761, 164475.88581619,
       221811.33272975, 171039.16994465, 155519.9057641 ,  54006.46382803,
       327890.6954896 , 122060.07450228, 170318.98032095, 230800.87313997,
       154809.78133091, 293306.51682808, 276986.48247264, 183236.81898625,
       270800.81416434, 126021.07888395, 258059.81145707, 298735.48918445,
       195388.62855659, 142769.27236527, 199174.23528447, 268236.40134126,
       332548.20105381, 142858.42531117, 132382.10049258, 125311.5214496 ,
       192470.68575328, 125115.83859986, 381863.18550324, 141456.09236901,
       183754.97041854,  

In [12]:
np.round(lr.score(x_test,y_test)*100)

68.0