In [1]:
import numpy as np
import pandas as pd
lungs=pd.read_csv("D:\\MLlab\\ML\\lung_cancer.csv")

In [2]:
lungs

Name      Surname  Age  Smokes  AreaQ  Alkhol  Result
0        John         Wick   35       3      5       4       1
1        John  Constantine   27      20      2       5       1
2      Camela     Anderson   30       0      5       2       0
3        Alex       Telles   28       0      8       1       0
4       Diego     Maradona   68       4      5       6       1
..        ...          ...  ...     ...    ...     ...     ...
114  Guinness        Alec    37      15      6       2       0
115    Heston    Charlton    34      12      8       0       0
116      Peck     Gregory    55      20      1       4       1
117   Poitier      Sidney    40      20      2       7       1
118     Smith       steven   28      20      2       8       1

[119 rows x 7 columns]

In [3]:
from sklearn.preprocessing import LabelEncoder
LabelEncoder=LabelEncoder()
lungs['Name']=LabelEncoder.fit_transform(lungs['Name'])
lungs['Surname']=LabelEncoder.fit_transform(lungs['Surname'])
lungs

Name  Surname  Age  Smokes  AreaQ  Alkhol  Result
0      49       94   35       3      5       4       1
1      49       15   27      20      2       5       1
2      12        2   30       0      5       2       0
3       1       91   28       0      8       1       0
4      19       60   68       4      5       6       1
..    ...      ...  ...     ...    ...     ...     ...
114    34        0   37      15      6       2       0
115    41       14   34      12      8       0       0
116    72       33   55      20      1       4       1
117    74       84   40      20      2       7       1
118    86       97   28      20      2       8       1

[119 rows x 7 columns]

In [19]:
x=lungs.iloc[:,0:-1].values
x

array([[49, 94, 35,  3,  5,  4],
       [49, 15, 27, 20,  2,  5],
       [12,  2, 30,  0,  5,  2],
       [ 1, 91, 28,  0,  8,  1],
       [19, 60, 68,  4,  5,  6],
       [17, 80, 34,  0, 10,  0],
       [65, 90, 58, 15, 10,  0],
       [52,  6, 22, 12,  5,  2],
       [68, 54, 45,  2,  6,  0],
       [75, 66, 52, 18,  4,  5],
       [30, 61, 33,  4,  8,  0],
       [96, 10, 18, 10,  6,  3],
       [48, 16, 25,  2,  5,  1],
       [45, 95, 28, 20,  2,  8],
       [ 3, 59, 34, 25,  4,  8],
       [51, 40, 39, 18,  8,  1],
       [51, 40, 42, 22,  3,  5],
       [ 4, 89, 19, 12,  8,  0],
       [58, 86, 62,  5,  4,  3],
       [32, 44, 73, 10,  7,  6],
       [46, 29, 55, 15,  1,  3],
       [64, 82, 33,  8,  8,  1],
       [33, 72, 22, 20,  6,  2],
       [84, 74, 44,  5,  8,  1],
       [76, 38, 77,  3,  2,  6],
       [56, 63, 21, 20,  5,  3],
       [71, 83, 37, 15,  6,  2],
       [79, 88, 34, 12,  8,  0],
       [50, 93, 55, 20,  1,  4],
       [31, 36, 40, 20,  2,  7],
       [62

In [20]:
y=lungs.iloc[:,-1].values
y

array([1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1], dtype=int64)

In [21]:
x.shape

(119, 6)

In [22]:
y.shape

(119,)

In [23]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split (x,y,test_size=0.25,random_state=0)

In [24]:
from sklearn.svm import SVC

In [25]:
svc1 = SVC(kernel="linear",gamma=10,C=1.0)
svc1.fit(x_train,y_train)

SVC(gamma=10, kernel='linear')

In [26]:
y_predict = svc1.predict(x_test)
y_predict [:10]

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int64)

In [27]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_predict,y_test)

In [28]:
print(cm)

[[20  2]
 [ 0  8]]


In [29]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_predict,y_test)
print(clf_report)

              precision    recall  f1-score   support

           0       1.00      0.91      0.95        22
           1       0.80      1.00      0.89         8

    accuracy                           0.93        30
   macro avg       0.90      0.95      0.92        30
weighted avg       0.95      0.93      0.94        30



In [30]:
from sklearn.metrics import accuracy_score
acc_score=accuracy_score(y_predict,y_test)

0.9333333333333333

In [31]:
np.round(acc_score*100,2)

93.33

In [32]:
new_x = [49,94,35,3,5,4]


In [33]:
y_predict=svc1.predict([new_x])
y_predict

array([1], dtype=int64)

In [34]:
from sklearn.preprocessing import StandardScaler
sd = StandardScaler()

In [36]:
X = sd.fit_transform(x)
X[:5]

array([[-0.00505057,  1.67263263, -0.46654014, -1.53356025, -0.07207945,
         0.30235616],
       [-0.00505057, -1.27864728, -0.96390432,  0.61938381, -1.29743019,
         0.72073271],
       [-1.39490429, -1.76430093, -0.77739276, -1.91349156, -0.07207945,
        -0.53439694],
       [-1.80810405,  1.56055871, -0.9017338 , -1.91349156,  1.15327128,
        -0.95277348],
       [-1.13195899,  0.40246153,  1.58508711, -1.40691649, -0.07207945,
         1.13910926]])