In [1]:
import pandas as pd
from numpy import*
import numpy as np

In [2]:
from sklearn import preprocessing

In [3]:
from sklearn import datasets, linear_model

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
from sklearn.metrics import accuracy_score

In [6]:
data=pd.read_csv("D:\\lab\\ML\\train_dataset.csv")

In [8]:
data

Gender  Age  openness  neuroticism  conscientiousness  agreeableness  \
0      Male   17         7            4                  7              3   
1      Male   19         4            5                  4              6   
2    Female   18         7            6                  4              5   
3    Female   22         5            6                  7              4   
4    Female   19         7            4                  6              5   
..      ...  ...       ...          ...                ...            ...   
704  Female   20         4            5                  6              6   
705    Male   18         6            3                  1              5   
706    Male   22         5            2                  3              6   
707    Male   19         5            6                  5              7   
708  Female   18         5            5                  7              6   

     extraversion Personality (Class label)  
0               2               extraverted  
1               6                   serious  
2               5                dependable  
3               3               extraverted  
4               4                    lively  
..            ...                       ...  
704             1               responsible  
705             5                dependable  
706             1                   serious  
707             5               extraverted  
708             5               extraverted  

[709 rows x 8 columns]

In [9]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [10]:
data

Gender  Age  openness  neuroticism  conscientiousness  agreeableness  \
0      Male   17         7            4                  7              3   
1      Male   19         4            5                  4              6   
2    Female   18         7            6                  4              5   
3    Female   22         5            6                  7              4   
4    Female   19         7            4                  6              5   
..      ...  ...       ...          ...                ...            ...   
704  Female   20         4            5                  6              6   
705    Male   18         6            3                  1              5   
706    Male   22         5            2                  3              6   
707    Male   19         5            6                  5              7   
708  Female   18         5            5                  7              6   

     extraversion Personality (Class label)  
0               2               extraverted  
1               6                   serious  
2               5                dependable  
3               3               extraverted  
4               4                    lively  
..            ...                       ...  
704             1               responsible  
705             5                dependable  
706             1                   serious  
707             5               extraverted  
708             5               extraverted  

[709 rows x 8 columns]

In [11]:
array=data.values

In [12]:
array.shape

(709, 8)

In [13]:
for i in range(len(array)):
    if array[i][0]=="Male":
        array[i][0]=1
    else:
        array[i][0]=0

In [14]:
array

array([[1, 17, 7, ..., 3, 2, 'extraverted'],
       [1, 19, 4, ..., 6, 6, 'serious'],
       [0, 18, 7, ..., 5, 5, 'dependable'],
       ...,
       [1, 22, 5, ..., 6, 1, 'serious'],
       [1, 19, 5, ..., 7, 5, 'extraverted'],
       [0, 18, 5, ..., 6, 5, 'extraverted']], dtype=object)

In [15]:
df=pd.DataFrame(array)

In [43]:
maindf=df[[0,1,2,3,4,5,6]]
maindf

0   1  2  3  4  5  6
0    1  17  7  4  7  3  2
1    1  19  4  5  4  6  6
2    0  18  7  6  4  5  5
3    0  22  5  6  7  4  3
4    0  19  7  4  6  5  4
..  ..  .. .. .. .. .. ..
704  0  20  4  5  6  6  1
705  1  18  6  3  1  5  5
706  1  22  5  2  3  6  1
707  1  19  5  6  5  7  5
708  0  18  5  5  7  6  5

[709 rows x 7 columns]

In [44]:
x_train=maindf.values
x_train

array([[1, 17, 7, ..., 7, 3, 2],
       [1, 19, 4, ..., 4, 6, 6],
       [0, 18, 7, ..., 4, 5, 5],
       ...,
       [1, 22, 5, ..., 3, 6, 1],
       [1, 19, 5, ..., 5, 7, 5],
       [0, 18, 5, ..., 7, 6, 5]], dtype=object)

In [18]:
temp=df[7]

In [19]:
temp=df[7]

In [20]:
y_train

array(['extraverted', 'serious', 'dependable', 'extraverted', 'lively',
       'lively', 'extraverted', 'extraverted', 'dependable', 'lively',
       'serious', 'extraverted', 'lively', 'dependable', 'responsible',
       'extraverted', 'serious', 'dependable', 'responsible',
       'extraverted', 'responsible', 'extraverted', 'responsible',
       'serious', 'serious', 'dependable', 'extraverted', 'extraverted',
       'lively', 'lively', 'extraverted', 'extraverted', 'dependable',
       'lively', 'serious', 'lively', 'responsible', 'responsible',
       'dependable', 'serious', 'dependable', 'extraverted', 'serious',
       'extraverted', 'dependable', 'dependable', 'responsible',
       'serious', 'lively', 'lively', 'extraverted', 'extraverted',
       'serious', 'extraverted', 'lively', 'lively', 'extraverted',
       'dependable', 'lively', 'lively', 'responsible', 'extraverted',
       'responsible', 'dependable', 'serious', 'serious', 'responsible',
       'dependable', 'respo

In [21]:
lr=linear_model.LogisticRegression(multi_class="multinomial",solver="newton-cg",max_iter=1000)

In [22]:
lr.fit(x_train,y_train)

LogisticRegression(max_iter=1000, multi_class='multinomial', solver='newton-cg')

In [23]:
y_predict_train=lr.predict(x_train)
y_predict_train

array(['lively', 'serious', 'extraverted', 'extraverted', 'dependable',
       'serious', 'extraverted', 'extraverted', 'serious', 'serious',
       'extraverted', 'dependable', 'serious', 'extraverted',
       'extraverted', 'extraverted', 'extraverted', 'extraverted',
       'extraverted', 'extraverted', 'serious', 'serious', 'responsible',
       'serious', 'extraverted', 'dependable', 'serious', 'extraverted',
       'extraverted', 'dependable', 'extraverted', 'lively',
       'extraverted', 'serious', 'extraverted', 'extraverted',
       'extraverted', 'extraverted', 'lively', 'extraverted',
       'responsible', 'extraverted', 'extraverted', 'extraverted',
       'serious', 'extraverted', 'extraverted', 'extraverted',
       'extraverted', 'serious', 'responsible', 'responsible', 'serious',
       'extraverted', 'dependable', 'lively', 'extraverted',
       'extraverted', 'serious', 'responsible', 'extraverted',
       'extraverted', 'extraverted', 'extraverted', 'dependable',
  

In [24]:
test_score=accuracy_score(y_train,y_predict_train)

In [25]:
training_accuracy=test_score*100

In [26]:
training_accuracy

24.118476727785616

In [27]:
testdata=pd.read_csv("D:\\lab\\ML\\test_dataset.csv")

In [28]:
test=testdata.values

In [29]:
test.shape

(315, 8)

In [30]:
for i in range(len(test)):
    if test[i][0]=="Male":
        test[i][0]=1
    else:
        test[i][0]=0

In [31]:
df1=pd.DataFrame(test)
testdf=df1[[0,1,2,3,4,5,6]]
x_test=testdf.values

In [32]:
print(x_test)

[[0 20 7 ... 9 5 5]
 [1 17 5 ... 5 2 4]
 [0 25 5 ... 7 2 4]
 ...
 [1 18 7 ... 6 2 7]
 [1 23 6 ... 5 4 3]
 [0 18 5 ... 3 5 6]]


In [33]:
y_predict_test=lr.predict(x_test)
y_predict_test

array(['dependable', 'serious', 'serious', 'serious', 'responsible',
       'serious', 'serious', 'serious', 'serious', 'serious', 'serious',
       'responsible', 'responsible', 'serious', 'lively', 'extraverted',
       'serious', 'serious', 'serious', 'extraverted', 'serious',
       'extraverted', 'serious', 'extraverted', 'serious', 'serious',
       'extraverted', 'extraverted', 'serious', 'responsible', 'serious',
       'lively', 'extraverted', 'lively', 'serious', 'serious', 'serious',
       'serious', 'extraverted', 'serious', 'responsible', 'responsible',
       'serious', 'lively', 'serious', 'serious', 'responsible',
       'dependable', 'serious', 'extraverted', 'serious', 'serious',
       'serious', 'lively', 'extraverted', 'serious', 'extraverted',
       'serious', 'serious', 'serious', 'responsible', 'serious',
       'dependable', 'serious', 'serious', 'responsible', 'serious',
       'serious', 'serious', 'serious', 'serious', 'serious', 'serious',
       'serious

In [34]:
y_test=df1[7].values

In [35]:
DF=pd.DataFrame(y_predict_test,columns=["predicted Personality"])

In [36]:
DF.index=DF.index+1

In [45]:
DF.index.names=["person No"]
DF

predicted Personality
person No                      
1                    dependable
2                       serious
3                       serious
4                       serious
5                   responsible
...                         ...
311                 extraverted
312                     serious
313                     serious
314                 extraverted
315                 extraverted

[315 rows x 1 columns]

In [38]:
DF.to_csv("output.csv")

In [39]:
out=pd.read_csv("output.csv")
out

person No predicted Personality
0            1            dependable
1            2               serious
2            3               serious
3            4               serious
4            5           responsible
..         ...                   ...
310        311           extraverted
311        312               serious
312        313               serious
313        314           extraverted
314        315           extraverted

[315 rows x 2 columns]

In [40]:
y_predict_test=lr.predict(x_test)
y_predict_test

array(['dependable', 'serious', 'serious', 'serious', 'responsible',
       'serious', 'serious', 'serious', 'serious', 'serious', 'serious',
       'responsible', 'responsible', 'serious', 'lively', 'extraverted',
       'serious', 'serious', 'serious', 'extraverted', 'serious',
       'extraverted', 'serious', 'extraverted', 'serious', 'serious',
       'extraverted', 'extraverted', 'serious', 'responsible', 'serious',
       'lively', 'extraverted', 'lively', 'serious', 'serious', 'serious',
       'serious', 'extraverted', 'serious', 'responsible', 'responsible',
       'serious', 'lively', 'serious', 'serious', 'responsible',
       'dependable', 'serious', 'extraverted', 'serious', 'serious',
       'serious', 'lively', 'extraverted', 'serious', 'extraverted',
       'serious', 'serious', 'serious', 'responsible', 'serious',
       'dependable', 'serious', 'serious', 'responsible', 'serious',
       'serious', 'serious', 'serious', 'serious', 'serious', 'serious',
       'serious

In [41]:
Test_score=accuracy_score(y_test,y_predict_test)
testing_accuracy=Test_score*100
testing_accuracy

85.71428571428571

In [42]:
y_predictnew=lr.predict([[0,19,7,4,6,5,4]])
y_predictnew

array(['dependable'], dtype=object)